---
apiVersion: v1
kind: Namespace
metadata:
  name: finops-engine
  labels:
    app.kubernetes.io/managed-by: argocd
    project: devops-platform

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-config
  namespace: finops-engine
data:
  USE_MOCK_DATA:          "true"
  LOOKBACK_DAYS:          "30"
  ANOMALY_THRESHOLD_PCT:  "30"
  DAILY_BUDGET_USD:       "10"
  MONTHLY_BUDGET_USD:     "100"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-engine
  namespace: finops-engine
  labels:
    app: finops-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-engine
  template:
    metadata:
      labels:
        app: finops-engine
    spec:
      containers:
        - name: finops-engine
          image: devopsplatformacr.azurecr.io/finops-engine:latest
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: finops-config
            - secretRef:
                name: finops-secrets
          resources:
            requests:
              cpu:    100m
              memory: 256Mi
            limits:
              cpu:    500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: finops-engine
  namespace: finops-engine
  labels:
    app: finops-engine
spec:
  selector:
    app: finops-engine
  ports:
    - port: 80
      targetPort: 8501
  type: ClusterIP
